[package]
name = "stateright"
version = "0.12.0"
authors = ["Jonathan Nadal <jon.nadal@gmail.com>"]
license = "MIT"
edition = "2018"

description = "A model checker for implementing distributed systems."
repository = "https://github.com/stateright/stateright"
readme = "README.md"
categories = ["actor", "concurrency", "development-tools", "network-programming", "simulation"]
keywords = ["actor", "distributed-systems", "model-checking", "paxos"]

[dependencies]
ahash = "0.3"
actix-web = "1.0"
crossbeam-utils = "0.7"
dashmap = "3.11"
id-set = "0.2.2"
log = "0.4"
nohash-hasher = "0.2.0"
rand = "0.7"
regex = "1.3"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
clap = "2.33"
env_logger = "0.7"
num_cpus = "1.13"
